-- 코드를 입력하세요
SELECT DATE_FORMAT(SALES_DATE, '%Y') AS YEAR, DATE_FORMAT(SALES_DATE, '%m') AS MONTH,GENDER, COUNT(DISTINCT B.USER_ID) AS USERS
FROM USER_INFO AS A
JOIN ONLINE_SALE AS B ON (A.USER_ID=B.USER_ID)
WHERE GENDER IS NOT NULL
GROUP BY 1,2,3
ORDER BY YEAR ASC, MONTH ASC, GENDER ASC